name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:

jobs:
  test:
    name: Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
